-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Memo CASCADE;

DROP TABLE IF EXISTS Category CASCADE;

DROP TABLE IF EXISTS Joint CASCADE;

DROP TABLE IF EXISTS UserAccount CASCADE;